sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
install:
  - npm install
script: npm test
git:
  submodules: false
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: k1CPvmSsWu6hxYX/gucbh+ng6HmRMqqsp6eL50iCmBvnZ7Qy4TPjfkLRfG8mJqxgFT4gPH4St2qxP16OMuIgZPZ1SUlUJxoDGDvMD7uaZXnuPHQgJbzNfC8fKaEBUhA4oqHgZv723v5kTmgpbcE0ec6MON3B5WbcbR0Hkkcqwed8ryCDqGQPgPfnoDRYRzIytagTBHVO1MJ3tdU8dfhIu/26/l77OSFJbIHHxQK6QSczZ0NGjKyezmvYNcpfVdIIk+1cZ05ymZP98GUDoH93aAYyFxb6A9qNPgjEhyEXRBg92v9CZHmLcbGpBhIhEseWYev8u24HYVaEncYKjJjPshML5XtQlNNNLi7eFQ6QjGumiuwpBdyXwi9AKBvAVPuLRfH9hRIKxeHuGS+3aUhHpNRdEBOatH8g8W5iKT4G7NyJtpJrXX2U5+Lr0MJQCMCNBnfFiR9IheTPxGwcwuHsFCKW/imBgPcQFUP1t1/B1rXmvmT+z5kR1TLvuuy7vfdJr0mpy0TL1XBc8Q4LZbj704CcacI9vvpvLu2JeGSw+YpvCvp3ZVtSMKDz9mOb8w3TiRh1Sgxae5MMGtHH5RKKlKHhi1lZjZBcond14q7u2a0cLKg9iT8YGWGz7aaaBQO7li6xmtO7gYvw6tEuMI4wgGfHF3n7qQin7CGD8LrsQsY=
  on:
    tags: true
    node_js: "7"
